### ISSUE TITLE
implement a function that makes DB-inserts 

### ISSUE THREAD

**Issue by destan** [dedeler/imdb-data-parser#11]
Preferably in another package. It shall be invoked by a separate command-line argument like --toDb. Also parsing into CSV be the default mode and this(--toDb) shall be another.

**Comment by destan** [comment]
You told me some sort of automation for script creation, what was it? Are you going to implement it shortly? Depending on this @aykutakin can begin generating SQLs for individual files.

**Comment by xaph** [comment]
@destan I couldn't remember anything about automation. I thought we should create sql files after parsing files. It could be something like

<pre>
//file output
self.outputFile.write(self.name + self.seperator + self.surname + self.seperator + matcher.group(2) + self.seperator + matcher.group(3) + self.seperator + matcher.group(4) + self.seperator + matcher.group(6) + self.seperator + matcher.group(7) + self.seperator + matcher.group(8) + self.seperator + matcher.group(9) + "\n")
//sql output
Xtable.write(self.name, self.surname, matcher.group(2), matcher.group(3)....)
</pre>
