### ISSUE TITLE
output file names need date

### ISSUE THREAD

**Issue by xaph** [dedeler/imdb-data-parser#14]
we need to stamp current date to output files to revisioning them.

movies.tsv -> movies-140120130745.tsv

**Comment by destan** [comment]
I think it would be better to leave file names untouched but put all of them into a folder named after the **start date** of export operation. Like:

```
/export/path/in/settings/
└── 02-FEB-2013
    ├── movies.list.tsv
    ├── directors.list.tsv
    ├── actors.list.tsv
    ├── genres.list.tsv
    ├── plot.list.tsv
```

**Comment by xaph** [comment]
It's ok but using name as 2013-02-02 (iso standart) may be much useful for use them again.

python has built-in function for iso format:

```
>>> import datetime
>>> d = datetime.date.today()
>>> d.isoformat()
'2013-01-17'
```
