### ISSUE TITLE
fucked lines must put into another output file

### ISSUE THREAD

**Issue by xaph** [dedeler/imdb-data-parser#15]
We should know which lines are fucked in each parse. So, wee need to put them into a file.

movies-140120130745.tsv parse  must create a file movies-140120130745.fucked

**Comment by aykutakin** [comment]
Some lines are seems fucked but actually they are out of range. For example, movies.list ends like '---------', so this seems like fucked but actually it means end of file. Another example is directors.list. There are many info line in the end of file. Maybe we need to check end of parsing with if(line='----')

**Comment by xaph** [comment]
@aykutakin you're right but I think discarding these lines isn't necessary now. we can log them now and discard later.
