### ISSUE TITLE
logs must printed inside files

### ISSUE THREAD

**Issue by xaph** [dedeler/imdb-data-parser#16]
we just need 2 log files as info.log and error.log

their paths can be configured from settings.py

printing logs to the console consumes time

**Comment by destan** [comment]
2013/1/14 Zafer CAKMAK

> printing logs to the console consumes time
> well, in terms of time I don't think there will be any difference between
> printing to a file or to the console.

**Comment by xaph** [comment]
$ time for i in {1..1000000}; do echo $i; done

real    0m16.693s
user    0m7.268s
sys 0m2.620s

$ time for i in {1..1000000}; do echo $i; done > hede.out

real    0m8.070s
user    0m6.412s
sys 0m1.552s

I asked this to Bekir and he said "Console uses a buffer and if it's full, the output process becomes blocking".
