### ISSUE TITLE
Utilize PIP for dependency management

### ISSUE THREAD

**Issue by destan** [dedeler/imdb-data-parser#29]

**Comment by yasakbulut** [comment]
removed unnecessary dependency (b0f067bad1bbaa2d403100ffa0ee6afe3bb4cca4), so the only remaining dependency is psycopg2. BUT psycopg2 depends on both Postgresql dev libs AND Python dev libs, both of which are un-installable via PIP. So, we face 2 choices here:
1. Keep the project as it is now, and let users' OS's package manager handle psycopg2 installation
2. Use PIP for dependencies, and list postgresql-dev and python-dev as external requirements
Waiting your comments on this. @destan, @aykutakin, @xaph

**Comment by xaph** [comment]
we won't use psycopg2 anymore :)

**Comment by yasakbulut** [comment]
So, we don't have dependencies anymore. What shall we use for dependency management?

```
Exception in thread "main" java.lang.NullPointerException
        at yasa.brain.Brain.processQuery(Brain.java:321358884)
```

**Comment by sollarman** [comment]
Hello guys ! We really dig your work on imdb parser and would like to support it. Also we need some custom features for our movie related startup.  Can we discuss it ?

Eugene.  
—

**Comment by destan** [comment]
Hi @sollarman , we are happy that you find the project useful. You are always welcome on developer e-mail list: imdb-data-parser-devel@dorukdestan.com

We would like to discuss feature requests and other possible contributions. You can also come by IRC channel `#dedeler` on `freenode`. But I am afraid this may not be an optimum meeting point because of time-zones but just have in mind that there we are on IRC as well :)

**Comment by sollarman** [comment]
Thanks for the answer ! I will get into the parser in the next couple of days and then I will provide valuable feedback.
