### ISSUE TITLE
Helper class/function to generate SQL files

### ISSUE THREAD

**Issue by destan** [dedeler/imdb-data-parser#30]
We shall generate sql files instead of inserting sql rows directly to the DB as per conversation in the devel-list.

This issue covers:
- Implementation of a helper class/function to generate SQL files
- abandoning and clearing DB configuration and related helpers

**Comment by destan** [comment]
@aykutakin, you can encourage @xaph to finish this issue fast so that you can start implementing SQL parts of parsers :)

Actually you could still start generating SQL strings for each parser yet let the file-writing part commented out.

**Comment by aykutakin** [comment]
@xaph I'm encouraging you: FINISH THIS F*CKING HELPER!!11!!
Is it enough:)

**Comment by yasakbulut** [comment]
@xaph do it

**Comment by xaph** [comment]
I'll deal with this tonight :)
