### ISSUE TITLE
When using latest build in SQL mode I am getting this:

### ISSUE THREAD

**Issue by sollarman** [dedeler/imdb-data-parser#33]
Zero bytes files

![Screen Shot 2013-03-10 at 5 37 13 PM](https://f.cloud.github.com/assets/597395/241197/9066e478-8998-11e2-9ff1-c4e876d2e92f.png)
It worked in TSV mode though.

Here is the log
![Screen Shot 2013-03-10 at 5 36 24 PM](https://f.cloud.github.com/assets/597395/241200/a48c3a20-8998-11e2-9591-bbc2b101799d.png)

**Comment by xaph** [comment]
SQL mode is at development process now. You can try TSV mode to get correct outputs.
