### ISSUE TITLE
determine which parsers are required

### ISSUE THREAD

**Issue by xaph** [dedeler/imdb-data-parser#6]
there are many files in imdb but we don't need most of them for now. we need to decide which ones are really required.
- [x] actors.list.gz [DONE]
- [x] actresses.list.gz [DONE]
- [ ] aka-names.list.gz
- [x] aka-titles.list.gz
- [ ] alternate-versions.list.gz
- [ ] biographies.list.gz
- [ ] business.list.gz
- [ ] certificates.list.gz
- [ ] cinematographers.list.gz
- [ ] color-info.list.gz
- [ ] complete-cast.list.gz
- [ ] complete-crew.list.gz
- [ ] composers.list.gz
- [ ] costume-designers.list.gz
- [ ] countries.list.gz
- [ ] crazy-credits.list.gz
- [x] directors.list.gz [DONE]
- [ ] distributors.list.gz
- [ ] editors.list.gz
- [ ] filesizes
- [ ] filesizes.old
- [x] genres.list.gz [DONE]
- [ ] german-aka-titles.list.gz
- [ ] goofs.list.gz
- [ ] iso-aka-titles.list.gz
- [ ] italian-aka-titles.list.gz
- [ ] keywords.list.gz
- [ ] language.list.gz
- [ ] laserdisc.list.gz
- [ ] literature.list.gz
- [ ] locations.list.gz
- [ ] miscellaneous-companies.list.gz
- [ ] miscellaneous.list.gz
- [ ] movie-links.list.gz
- [x] movies.list.gz [DONE]
- [ ] mpaa-ratings-reasons.list.gz
- [x] plot.list.gz [DONE]
- [ ] producers.list.gz
- [ ] production-companies.list.gz
- [ ] production-designers.list.gz
- [ ] quotes.list.gz
- [x] ratings.list.gz [DONE]
- [ ] release-dates.list.gz
- [x] running-times.list.gz
- [ ] sound-mix.list.gz
- [ ] soundtracks.list.gz
- [ ] special-effects-companies.list.gz
- [x] taglines.list.gz
- [ ] technical.list.gz
- [x] trivia.list.gz [DONE]
- [x] writers.list.gz

**Comment by xaph** [comment]
I think we need to consider about these files:

names vs titles??? we can show alternative names
aka-names.list.gz
aka-titles.list.gz

alternate-versions.list.gz -> if this gives similar movies, we must include this.

crew vs cast??? we can list them
complete-cast.list.gz
complete-crew.list.gz  

keywords.list.gz  -> may used for keyword based filter & rand
movie-links.list.gz  -> may useful to give extended links

**Comment by destan** [comment]
I have added complete-cast. let's focus on what we have for now, once we are done with all these adding new parsers should be trivial.

I am closing this issue and creating new ones for every file to be pared.
