### ISSUE TITLE
find imdb_id from internet 

### ISSUE THREAD

**Issue by destan** [dedeler/imdb-data-parser#8]

**Comment by xaph** [comment]
we may use http://www.omdbapi.com/ to get id's.

**Comment by destan** [comment]
you mentioned freebase or smth. before. Can you work on this?

**Comment by yasakbulut** [comment]
fear no more, for I've blessed you with a new tool! Check it out! 48554a18fda16e0d9ef77fa4d9587f58d6865339 

We can merge this to master once we test this thoroughly.

**Comment by xaph** [comment]
@yasakbulut we're already in pre-alpha state. you can merge it with master without testing. Everybody works at master now. join us now and share the software :)

**Comment by yasakbulut** [comment]
![nLEs8](https://f.cloud.github.com/assets/676957/221637/d8ec1d60-85a3-11e2-99db-e7cfcf13f6c2.gif)

**Comment by xaph** [comment]
![clapping](https://f.cloud.github.com/assets/124090/221655/706f88fc-85a4-11e2-9fe4-cfea53a9218f.gif)

**Comment by destan** [comment]
order! order in the repo!
